TRAIN_MODEL: true
EPOCHS: 100

NAME: segmentation
SAVE: true
SEED: null
PARSER: false
CONVERT_TO_TFLITE: false

BASE_PATH: '/home/david/SemesterProject/Models'

LOSS:
  edge: null
  segmentation: true
  vert: null
  cont: null
  flow: null

LR:
  START:  0.005
  END:    0.0001
  POWER: 0.9

CALLBACKS:
  DEL_OLD_CKPT: true
  CKPT_FREQ: 10
  DEL_OLD_TB: true
  LOG_TB: false
  TENSORBOARD: false