NAME: edge_detection

BASE_PATH_DATA: /home/david/SemesterProject/Datasets
DATASET_JSON: dataset.json

# mask encoding types: 0: INSTANCE, 1: CATEGORY, 2: BINARY
in:
  img:
    name: "in_img"
    shape: [ 640, 360 ]
  edge: null
  contour: null
  segmentation: null
  prior_img: null

out:
  edge:
    name: "out_edge"
    mask_encoding: 2
    shape: [ 320, 180 ]
  contour: null
  segmentation: null
  flow: null

# DATASETS:
TEST:
  NAME: Test
  MAX_IMG: 300

  BATCH_SIZE: 5
  # BATCH_SIZE: 1
  CACHE: true
  SHUFFLE: false
  PREFETCH: true

  DATA_AUGMENTATION: null

TRAIN:
  NAME: Train
  MAX_IMG: 1500

  BATCH_SIZE: 5
  # BATCH_SIZE: 1
  CACHE: true
  SHUFFLE: true
  PREFETCH: true

  DATA_AUGMENTATION: null

REAL_WORLD:
  PATH: /home/david/SemesterProject/Datasets/real_world

  MAX_IMG: 100

  BATCH_SIZE: 3

  CACHE: true
  SHUFFLE: false
  PREFETCH: true

  DATA_AUGMENTATION: null
