NAME: edge_detection

BASE_PATH_DATA: /home/david/SemesterProject/Datasets
DATASET_JSON: dataset.json

# mask encoding types: 0: INSTANCE, 1: CATEGORY, 2: BINARY
in:
  img:
    name: "in_img"
    shape: [ 640, 360 ]
  edge: null
  contour: null
  segmentation: null
  prior_img: null

out:
  edge:
    name: "out_edge"
    mask_encoding: 2
    shape: [ 320, 180 ]
  contour: null
  segmentation: null
  flow: null

# DATASETS:
TEST:
  NAME: Test
  MAX_IMG: 300

  BATCH_SIZE: 5
  # BATCH_SIZE: 1
  CACHE: true
  SHUFFLE: false
  PREFETCH: true

  DATA_AUG: null

TRAIN:
  NAME: Train
  MAX_IMG: 1500

  BATCH_SIZE: 5
  # BATCH_SIZE: 1
  CACHE: true
  SHUFFLE: true
  PREFETCH: true

  DATA_AUG:
    blur: false
    brightness: 0.15
    contrast_factor: 0.85
    gaussian_value: 0.015
    hue: 0.05
    noise_std: 0.0
    saturation: 0.8
    sigma: 1.0
    strength_spot: 0.3
    value: 0.1

IMG_ONLY:
  PATH: 'Real'

  MAX_IMG: 100

  BATCH_SIZE: 3

  CACHE: true
  SHUFFLE: false
  PREFETCH: true

  DATA_AUG: null
