NAME: edge_detection

BASE_PATH_DATA: /home/david/SemesterProject/Datasets
DATASET_JSON: dataset.json

MASK_TYPE: # 0: INSTANCE, 1: CATEGORY
  edge: 2
  cont: 1
  vert: 1

in:
  edge: false
  vert: false
  cont: false
  prior_img: false

out:
  edge: true
  vert: false
  cont: false
  flow_edge: false
  flow_scene: false

# As already implemented just as additional information and example on how to load
VERT_LIST: false


# DATASETS:
TEST:
  NAME: Test
  MAX_IMG: 300

  BATCH_SIZE: 3
  # BATCH_SIZE: 1
  CACHE: true
  SHUFFLE: false
  PREFETCH: true

  DATA_AUGMENTATION: null

TRAIN:
  NAME: Train
  MAX_IMG: 1500

  BATCH_SIZE: 3
  # BATCH_SIZE: 1
  CACHE: true
  SHUFFLE: true
  PREFETCH: true

  DATA_AUGMENTATION: null

REAL_WORLD:
  PATH: /home/david/SemesterProject/Datasets/real_world

  MAX_IMG: 100

  BATCH_SIZE: 3

  CACHE: true
  SHUFFLE: false
  PREFETCH: true

  DATA_AUGMENTATION: null
