TRAIN_MODEL: true
EPOCHS: 60

NAME: lite_edge
SAVE: true
INPUT_SHAPE_IMG: [ 640, 360 ]
OUTPUT_SHAPE: [ 320, 180 ]
SEED: null
PARSER: false
CONVERT_TO_TFLITE: true

# Model type: defines the task which is solved by the model ['edge detector']
MODEL:
  TYPE: 'edge detector'
  DILATION: false

BACKBONE:
  NAME: MobileNetV2
  ALPHA: 1.0
  WEIGHTS: imagenet
  OUTPUT_IDS: [2, 3, 4, 5, 6, 8]
  TRAIN_IDX: null

  FINE_TUNING:
    EPOCHS: 5
    FINE_TUNING: false

LOSS:
  edge:
    sigmoid:
      apply: false
      class_individually_weighted: true
      min_edge_loss_weighting: 0.4
      max_edge_loss_weighting: 0.6
    focal:
      apply: true
      edge_loss_weighting: true
      min_edge_loss_weighting: 0.4
      max_edge_loss_weighting: 0.6
      power: 1.0
  vert: null
  cont: null
  flow_edge: null
  flow_scene: null

LR:
  START: 0.005
  END: 0.0005
  POWER: 0.9

CALLBACKS:
  DEL_OLD_CKPT: true
  CKPT_FREQ: 10
  DEL_OLD_TB: true
  LOG_TB: false
  TENSORBOARD: false

CATEGORIES:
  edge: 1
#  base: 1
#  bar: 2
#  cover: 3
#  elektro: 4
#  tube: 5
