TRAIN_MODEL: true
EPOCHS: 200

NAME: lite_edge
SAVE: true
INPUT_SHAPE_IMG: [ 320, 180 ]
OUTPUT_SHAPE: [ 320, 180 ]
SEED: null
PARSER: false
CONVERT_TO_TFLITE: true

BACKBONE:
  NAME: MobileNetV2
  ALPHA: 1.0
  WEIGHTS: imagenet
  OUTPUT_IDS: [2, 3, 4, 5, 6, 8]
  TRAIN_IDX: null

PADDING: 2                          # Num of Pixels at border of output, for which no loss function is applied
NUM_PIXELS_REGION_OF_ATTRACTION: 1

LOSS:
  edge:
    sigmoid:
      apply: true
      # if edge_loss_weighting is false: weighted with inverse frequency
      edge_loss_weighting: true
      max_edge_loss_weighting_edge: 0.9
      max_edge_loss_weighting_non_edge: 0.7
      min_edge_loss_weighting_region_of_attraction: 0.1
      min_edge_loss_weighting_non_edge: 0.3
    focal:
      apply: false
      # if edge_loss_weighting is false: weighted with inverse frequency
      edge_loss_weighting: true
      max_edge_loss_weighting_edge: 0.9
      max_edge_loss_weighting_non_edge: 0.7
      min_edge_loss_weighting_region_of_attraction: 0.1
      min_edge_loss_weighting_non_edge: 0.3
      power: 4.0
      decay: true
      focal_loss_derivative_threshold: 0.05
  vert: null
  segmentation: null
  cont: null
  flow: null

LR:
  START:  0.01
  END:    0.00005
  POWER: 0.9

CALLBACKS:
  DEL_OLD_CKPT: true
  CKPT_FREQ: 20
  DEL_OLD_TB: true
  LOG_TB: false
  TENSORBOARD: false

# For Transformation to TFLite. Add the name and category label
CATEGORIES:
  edge: 1