NAME: edge_detection

BASE_PATH_DATA: /home/david/SemesterProject/Datasets
DATASET_JSON: dataset.json

# mask encoding types: 0: INSTANCE, 1: CATEGORY, 2: BINARY
in:
  img:
    name: "in_img"
    shape: [320, 180]
  edge:
    name: "in_edge"
    mask_encoding: 2
    shape: [ 80, 45 ]
  contour: null
#    name: "in_contour"
#    mask_encoding: 2
#    shape: [ 80, 45 ]
    #name: "in_vert"
  segmentation: null
    #name: "in_segmentation"
  prior_img: null
    #name: "in_prior_img"

out:
  edge:
    name: "out_edge"
    mask_encoding: 2
    shape: [ 320, 180 ]
  contour: null
  segmentation: null
    #name: "out_segmentation"
  flow: null
    #name: "out_flow"
    #only_edge: true
    #shape: [ 80, 45 ]


# DATASETS:
TEST:
  NAME: Test
  MAX_IMG: 300

  BATCH_SIZE: 5
  # BATCH_SIZE: 1
  CACHE: true
  SHUFFLE: false
  PREFETCH: true

  DATA_AUG: null

TRAIN:
  NAME: Train
  # MAX_IMG: 1500
  MAX_IMG: 1500

  BATCH_SIZE: 5
  # BATCH_SIZE: 1
  CACHE: true
  SHUFFLE: true
  PREFETCH: true

  DATA_AUG: null
#    blur: false
#    brightness: 0.0
#    contrast_factor: 0.75
#    gaussian_value: 0.75
#    hue: 0.1
#    noise_std: 0
#    saturation: 0.75
#    sigma: 1.0
#    strength_spot: 0.3
#    value: 0.3

IMG_ONLY:
  PATH: 'real'

  MAX_IMG: 10

  BATCH_SIZE: 5

  CACHE: true
  SHUFFLE: false
  PREFETCH: true

  DATA_AUG: null
