TRAIN_MODEL: true                   # If a new model should be trained or just loaded
EPOCHS: 200                         # Number of Epochs

NAME: edge_detection_with_prior     # Name of the Network Architecture
SAVE: true                          # If the Model and Figures should be Save
SEED: null                          # For the random data generator used by Data Augmentation and Shuffling
PARSER: false
CONVERT_TO_TFLITE: true

PADDING: 2                          # Num of Pixels at border of output, for which no loss function is applied
PIXELS_AT_EDGE_WITHOUT_LOSS: 1

LOSS:
  edge:
    sigmoid:
      apply: true
      class_individually_weighted: false
      # Values are set, such that recall and precision are similar
      min_edge_loss_weighting: 0.15
      max_edge_loss_weighting: 0.85
    focal:
      apply: false
      edge_loss_weighting: true
      # Values are set, such that recall and precision are similar
      min_edge_loss_weighting: 0.2
      max_edge_loss_weighting: 0.8
      power: 4.0
      decay: true
      focal_loss_derivative_threshold: 0.05
  vert: null
  segmentation: null
  cont: null
  flow: null

LR:
  START:  0.01
  END:    0.00005
  POWER: 0.9

CALLBACKS:
  DEL_OLD_CKPT: true
  CKPT_FREQ: 20
  DEL_OLD_TB: true
  LOG_TB: false
  TENSORBOARD: false

# For Transformation to TFLite. Add the name and category label
CATEGORIES:
  edge: 1
