TRAIN_MODEL: true
EPOCHS: 80

NAME: edge_detection_with_prior
SAVE: true
INPUT_SHAPE: [ 640, 360 ]
OUTPUT_SHAPE: [ 320, 180 ]
SEED: null
PARSER: false
CONVERT_TO_TFLITE: true

# Model type: defines the task which is solved by the model ['edge detector']
MODEL:
  TYPE: 'edge detector'

BACKBONE:
  NAME: MobileNetV2
  ALPHA: 0.35
  WEIGHTS: imagenet
  # OUTPUT_IDX: &idx 5
  # OUTPUT_IDS: [1, 2, 3, *idx]
  OUTPUT_IDX: &idx 3
  OUTPUT_IDS: [1, 2, *idx]
  TRAIN_IDX: null

  FINE_TUNING:
    EPOCHS: 5
    FINE_TUNING: false

LOSS:
  edge:
    sigmoid:
      apply: false
      class_individually_weighted: true
      min_edge_loss_weighting: 0.0005
      max_edge_loss_weighting: 0.9995
    focal:
      apply: true
      edge_loss_weighting: true
      min_edge_loss_weighting: 0.5
      max_edge_loss_weighting: 0.5
      power: 4.0
  vert: null
  cont: null
  flow_edge: null
  flow_scene: null

LR:
  START: 0.015
  END: 0.0005
  POWER: 0.9

CALLBACKS:
  DEL_OLD_CKPT: true
  CKPT_FREQ: 10
  DEL_OLD_TB: true
  LOG_TB: false
  TENSORBOARD: false

CATEGORIES:
  base: 1
  bar: 2
  cover: 3
  elektro: 4
  tube: 5
