NAME: dataset_with_flow_field

BASE_PATH_DATA: /home/david/SemesterProject/Datasets
DATASET_JSON: dataset.json

# mask encoding types: 0: INSTANCE, 1: CATEGORY, 2: BINARY
in:
  img:
    name: "in_img"
    shape: [640, 360]
  edge:
    name: "in_edge"
    mask_encoding: 2
    shape: [ 160, 90 ]
  contour: null
  segmentation: null
  prior_img: null

out:
  edge:
    name: "out_edge"
    mask_encoding: 2
    shape: [ 160, 90 ]
  contour: null
  segmentation: null
  flow:
    name: "out_flow"
    only_edge: true
    shape: [ 20, 12 ]


# DATASETS:
TEST:
  NAME: Test
  MAX_IMG: 300

  BATCH_SIZE: 3
  # BATCH_SIZE: 1
  CACHE: true
  SHUFFLE: false
  PREFETCH: true

  DATA_AUG: null

TRAIN:
  NAME: Train
  # MAX_IMG: 1500
  MAX_IMG: 1500

  BATCH_SIZE: 3
  # BATCH_SIZE: 1
  CACHE: true
  SHUFFLE: true
  PREFETCH: true

  DATA_AUG: null

IMG_ONLY: null
#  PATH: 'real_world'
#
#  MAX_IMG: 41
#
#  BATCH_SIZE: 5
#
#  CACHE: true
#  SHUFFLE: false
#  PREFETCH: true
#
#  DATA_AUG: null
