TRAIN_MODEL: true
EPOCHS: 1000

NAME: flow_edge
SAVE: true
SEED: null
PARSER: false
CONVERT_TO_TFLITE: false

PADDING: 2
PIXELS_AT_EDGE_WITHOUT_LOSS: 1

BACKBONE:
  NAME: MobileNetV2
  ALPHA: 0.35
  WEIGHTS: imagenet
  # OUTPUT_IDX: &idx 3
  # OUTPUT_IDS: [1, 2, *idx]
  OUTPUT_IDX: &idx 2
  OUTPUT_IDS: [1, *idx]
  TRAIN_IDX: null

  FINE_TUNING:
    EPOCHS: 5
    FINE_TUNING: false

LOSS:
  edge:
    sigmoid:
      apply: false
      class_individually_weighted: false
      # Values are set, such that recall and precision are similar
      min_edge_loss_weighting: 0.15
      max_edge_loss_weighting: 0.85
    focal:
      apply: true
      edge_loss_weighting: true
      # Values are set, such that recall and precision are similar
      min_edge_loss_weighting: 0.2
      max_edge_loss_weighting: 0.8
      power: 4.0
      decay: true
      focal_loss_derivative_threshold: 0.05
  vert: null
  segmentation: null
  cont: null
  flow: True

LR:
  START:  0.001
  END:    0.00005
  POWER: 0.9

CALLBACKS:
  DEL_OLD_CKPT: true
  CKPT_FREQ: 10
  DEL_OLD_TB: true
  LOG_TB: false
  TENSORBOARD: false

CATEGORIES:
  edge: 1