NAME: flow

BASE_PATH_DATA: /home/david/SemesterProject/Datasets
DATASET_JSON: dataset.json

# 0: INSTANCE, 1: CATEGORY, 2: BINARY
MASK_TYPE:
  edge: 2
  cont: 1
  vert: 1

in:
  edge: false
  vert: false
  cont: false
  prior_img: true

out:
  edge: false
  vert: false
  cont: false
  flow_edge: false
  flow_scene: true

# As already implemented just as additional information and example on how to load
VERT_LIST: false


# DATASETS:
TEST:
  NAME: Test
  MAX_IMG: 100

  BATCH_SIZE: 5
  # BATCH_SIZE: 1
  CACHE: true
  SHUFFLE: false
  PREFETCH: true

  DATA_AUG: null

TRAIN:
  NAME: Train
  # MAX_IMG: 1500
  MAX_IMG: 1500

  BATCH_SIZE: 5
  # BATCH_SIZE: 1
  CACHE: true
  SHUFFLE: true
  PREFETCH: true

  DATA_AUG: null
#    blur: false
#    brightness: 0.2
#    contrast_factor: 0.7
#    gaussian_value: 0.0
#    hue: 0.05
#    noise_std: 0.0
#    saturation: 0.7
#    sigma: 1.0
#    strength_spot: 0.1
#    value: 0.1

IMG_ONLY: null
