NAME: edge_detection

BASE_PATH_DATA: /home/david/SemesterProject/Datasets
DATASET_JSON: dataset.json


# mask encoding types: 0: INSTANCE, 1: CATEGORY, 2: BINARY
in:
  img:
    name: "in_img"
    shape: [320, 180]
  edge: null
  contour: null
  segmentation: null
  prior_img: null

out:
  edge:
    name: "out_edge"
    mask_encoding: 2
    shape: [ 320, 180 ]
  contour: null
  segmentation: null
    #name: "out_segmentation"
  flow: null

# As already implemented just as additional information and example on how to load
VERT_LIST: false


# DATASETS:
TEST:
  NAME: Test
  MAX_IMG: 300

  BATCH_SIZE: 5
  # BATCH_SIZE: 1
  CACHE: true
  SHUFFLE: false
  PREFETCH: true

  DATA_AUG: null

TRAIN:
  NAME: Train
  MAX_IMG: 1500

  BATCH_SIZE: 5
  # BATCH_SIZE: 1
  CACHE: true
  SHUFFLE: true
  PREFETCH: true

  DATA_AUG:
#    blur: false
#    brightness: 0.2
#    contrast_factor: 0.8
#    gaussian_value: 0.0
#    hue: 0.025
#    noise_std: 0
#    saturation: 0.8
#    sigma: 1.0
#    strength_spot: 0.3
#    value: 0.3

IMG_ONLY:
  PATH: 'Real'

  MAX_IMG: 100

  BATCH_SIZE: 3

  CACHE: true
  SHUFFLE: false
  PREFETCH: true

  DATA_AUG: null
