TRAIN_MODEL: false                   # If a new model should be trained or just loaded
EPOCHS: 200                         # Number of Epochs

NAME: edge_detection_without_prior  # Name of the Network Architecture
SAVE: true                          # If the Model and Figures should be Save
SEED: null                          # For the random data generator used by Data Augmentation and Shuffling
PARSER: false
CONVERT_TO_TFLITE: true

PADDING: 2                          # Num of Pixels at border of output, for which no loss function is applied
NUM_PIXELS_REGION_OF_ATTRACTION: 1

LOSS:
  edge:
    sigmoid:
      apply: true
      # if edge_loss_weighting is false: weighted with inverse frequency
      edge_loss_weighting: true
      max_edge_loss_weighting_edge: 0.9
      max_edge_loss_weighting_non_edge: 0.7
      min_edge_loss_weighting_region_of_attraction: 0.1
      min_edge_loss_weighting_non_edge: 0.3
    focal:
      apply: false
      # if edge_loss_weighting is false: weighted with inverse frequency
      edge_loss_weighting: true
      max_edge_loss_weighting_edge: 0.9
      max_edge_loss_weighting_non_edge: 0.7
      min_edge_loss_weighting_region_of_attraction: 0.1
      min_edge_loss_weighting_non_edge: 0.3
      power: 4.0
      decay: true
      focal_loss_derivative_threshold: 0.05
  vert: null
  segmentation: null
  cont: null
  flow: null

LR:
  START:  0.01
  END:    0.0001
  POWER: 0.9

CALLBACKS:
  DEL_OLD_CKPT: true
  CKPT_FREQ: 20
  DEL_OLD_TB: true
  LOG_TB: false
  TENSORBOARD: false

# For Transformation to TFLite. Add the name and category label
CATEGORIES:
  edge: 1
